=== bowring/SquidParametersManager/SquidParametersManagerApp/refmatschema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ReferenceMaterial">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="modelName"/>
        <xs:element type="xs:float" name="version"/>
        <xs:element type="xs:string" name="labName"/>
        <xs:element type="xs:date" name="dateCertified"/>
        <xs:element type="xs:string" name="references"/>
        <xs:element type="xs:string" name="comments"/>
        <xs:element name="values">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ValueModel" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:float" name="value"/>
                    <xs:element type="xs:string" name="uncertaintyType"/>
                    <xs:element type="xs:byte" name="oneSigma"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="concentrations">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ValueModel" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:float" name="value"/>
                    <xs:element type="xs:string" name="uncertaintyType"/>
                    <xs:element type="xs:float" name="oneSigma"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bowring/SquidParametersManager/SquidParametersManagerApp/referencematerial.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
    *****************************************************************************
    * This XML file was generated by ET_Redux.                                  *
    * For more info, visit https://CIRDLES.org                                  *
    *****************************************************************************
-->
<ReferenceMaterial  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="refmatschema.xsd">
    <modelName>Temora Placeholder</modelName>
    <version>1.0</version>
    <labName>EARTHTIME</labName>
    <dateCertified>2016-02-21</dateCertified>
    <references>No references</references>
    <comments>No comments</comments>
    <values>
        <ValueModel>
            <name>r206_207r</name>
            <value>0.00000000000000000000</value>
            <uncertaintyType>ABS</uncertaintyType>
            <oneSigma>0</oneSigma>
            <measured>false</measured>
        </ValueModel>
        <ValueModel>
            <name>r206_208r</name>
            <value>0.00000000000000000000</value>
            <uncertaintyType>ABS</uncertaintyType>
            <oneSigma>0</oneSigma>
            <measured>false</measured>
        </ValueModel>
        <ValueModel>
            <name>r206_238r</name>
            <value>0.00000000000000000000</value>
            <uncertaintyType>ABS</uncertaintyType>
            <oneSigma>0</oneSigma>
            <measured>false</measured>
        </ValueModel>
        <ValueModel>
            <name>r208_232r</name>
            <value>0.00000000000000000000</value>
            <uncertaintyType>ABS</uncertaintyType>
            <oneSigma>0</oneSigma>
            <measured>false</measured>
        </ValueModel>
        <ValueModel>
            <name>r238_235s</name>
            <value>0.00000000000000000000</value>
            <uncertaintyType>ABS</uncertaintyType>
            <oneSigma>0</oneSigma>
            <measured>false</measured>
        </ValueModel>
    </values>
    <concentrations>
        <ValueModel>
            <name>concU</name>
            <value>0.00000000000000000000</value>
            <uncertaintyType>ABS</uncertaintyType>
            <oneSigma>0.00000000000000000000</oneSigma>
        </ValueModel>
        <ValueModel>
            <name>concTh</name>
            <value>0.00000000000000000000</value>
            <uncertaintyType>ABS</uncertaintyType>
            <oneSigma>0.00000000000000000000</oneSigma>
        </ValueModel>
    </concentrations>
</ReferenceMaterial>
